### PR TITLE
Updated with MRR ESPE pins

### PR DESCRIPTION
**Pull request by vivian-ng**
Added the pins file for the MRR ESPE, which is an experimental ESP32-based board supporting I2S.

### CODE REVIEW

**Comment by luc-github** [comment]
that is just than adding pins, can you your changes using my latest fork ?

**Comment by luc-github** [comment]
45 commits is too many changes
if only pins files -  it should affect 
* Marlin/src/core/boards.h  
* Marlin/src/pins/pins.h 
* Files in  Marlin/src/pins/esp32

**Comment by vivian-ng** [comment]
@luc-github My bad, I am still learning how to properly use git. Ending up with unnecessary commits and all kinds of mistakes.

I have made the changes. The only things that should have changed would be the pins-related files. Plus the index.html.gz, which I have updated to the latest 2.1b50 that I downloaded directly from the ESP3D-WEBUI repo.

**Comment by luc-github** [comment]
I see also pins_ESP32_FS_ENDER3.h
this is also to be merged ? where it come from ?

**Comment by vivian-ng** [comment]
`pins_ESP32_FS_ENDER3.h`
is the pins definition file for felixstorm's custom board. If you are not open to adding this board, I can remove it.

**Comment by luc-github** [comment]
I am fine - I just try to isolate the changes which need to import as your PR only mention MRR ESPE pins ^_^

**Comment by vivian-ng** [comment]
I can remove it. It is not in the official repo yet anyway. More for my reference than anything.

**Comment by luc-github** [comment]
any reason you changed 
`#define BOARD_MRR_ESPA                6001`
to
`#define BOARD_MRR_ESPA                6010`

may be naming a rule I am not aware of ?

**Comment by vivian-ng** [comment]
> any reason you changed
#define BOARD_MRR_ESPA 6001
to
#define BOARD_MRR_ESPA 6010
may be naming a rule I am not aware of ?

No, just in anticipation of a future push back to the main Marlin repo by you, and in case by then, some other people have other ESP32 board defs in the main repo. 😅

**Comment by luc-github** [comment]
well in current state I do not know well I will get answer, anyway no worry when this will happen I will do some adjustment before, I think better to keep current numbering in case no one did ;)

**Comment by luc-github** [comment]
I will do import today

**Comment by luc-github** [comment]
I have applied these changes based on your repository content
Let me know if need more

**Comment by luc-github** [comment]
@vivian-ng so can I close this PR ?

**Comment by vivian-ng** [comment]
@luc-github Thank you for applying the changes!

**Pull request closed without merging**
